### PR TITLE
af_za change

### PR DESCRIPTION
**Pull request by HigherLight**

### CODE REVIEW

**Comment by xf8b** [comment]
r u updating or adding new thing
cuz this already exists

**Comment by HigherLight** [comment]
update beetch

**Comment by xf8b** [comment]
ur translation faulty then cuz u didnt translate 'config value'

**Comment by xf8b** [comment]
update when ready

**Comment by HigherLight** [comment]
dude u said i shouldnt translate the things in brackets smh

**Comment by xf8b** [comment]
wat

**Comment by xf8b** [comment]
efiaegaegjeragaeskrogaerg

**Comment by xf8b** [comment]
i will manually edit the file

**Pull request closed without merging**
